services:
  minecraft:
    image: itzg/minecraft-server
    ports:
      - 25565:25565
    environment:
      - EULA=TRUE
      - TYPE=CUSTOM
      - CUSTOM_SERVER=https://storage.googleapis.com/orca-buckets/Rancha.jar
      - MEMORY=1G
      - TZ=America/Chicago
    tty: true
    stdin_open: true
    volumes:
      - ./minecraft-data:/data
    depends_on:
      - mariadb
  
  mariadb:
    image: mariadb:latest
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=rootpass0521
      - MARIADB_DATABASE=survivalgames
      - MARIADB_USER=minecraft
      - MARIADB_PASSWORD=ilchepo0521
    volumes:
      - mariadb_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_HOST=mariadb
      - PMA_USER=minecraft
      - PMA_PASSWORD=ilchepo0521
    depends_on:
      - mariadb

volumes:
  mariadb_data: