version: '3'

services:
  minecraft:
    image: itzg/minecraft-server
    ports:
      - 25565:25565
    environment:
      - EULA=TRUE
      - TYPE=PAPER
      - MEMORY=4G
    tty: true
    stdin_open: true