services:
  minecraft:
    image: itzg/minecraft-server
    ports:
      - 25565:25565
    environment:
      - EULA=TRUE
      - TYPE=CUSTOM
      - CUSTOM_SERVER=https://storage.googleapis.com/orca-buckets/Rancha.jar
      - MEMORY=4G
      - TZ=America/Chicago
    tty: true
    stdin_open: true
    volumes:
      - ./data:/data
volumes:
  data: {}